import org.scalajs.sbtplugin.ScalaJSPlugin.AutoImport._
import sbt._
import sbt.Keys._

object KazariBuild {
  def concatFiles(path: String, filesToConcat: Seq[String], fileResult: String): Unit = {
    val concatFile = new File(path + "/" + fileResult)
    IO.delete(concatFile)
    IO.touch(concatFile)
    for (file <- filesToConcat.map((f) => new File(path + "/" + f))) {
      val content = IO.read(file)
      IO.append(concatFile, content)
    }
  }

  lazy val kazariDefaultPath =
    settingKey[String]("Default path where the scripts generated by Scala.JS live")
  lazy val kazariPluginFilename =
    settingKey[String]("Filename of the resulting generated javascript plugin")
  lazy val fastOptSuffix = settingKey[String](
    "Suffix used by Scala.JS to name the main script generated as a result of a fastOptJS task")
  lazy val fullOptSuffix = settingKey[String](
    "Suffix used by Scala.JS to name the main script generated as a result of a fullOptJS task")
  lazy val jsDepSuffix = settingKey[String](
    "Suffix used by Scala.JS to name the dependencies script generated as a result of a fastOptJS/fullOptJS task")

  lazy val jsFastOptAssembleTask = TaskKey[Unit](
    "fastOptAssemble",
    "Assembles Scala.JS dependencies and the script generated as a result of executing fastOptJs in a single file")
  lazy val jsFastOptGenerateTask = TaskKey[Unit](
    "fastOptGenerate",
    "Perform a call to Scala.JS's fastOptJS task, and then combines the resulting scripts in a single file")
  lazy val jsFullOptAssembleTask = TaskKey[Unit](
    "fullOptAssemble",
    "Assembles Scala.JS dependencies and the script generated as a result of executing fullOptJs in a single file")
  lazy val jsFullOptGenerateTask = TaskKey[Unit](
    "fullOptGenerate",
    "Perform a call to Scala.JS's fullOptJs task, and then combines the resulting scripts in a single file")

  lazy val kazariTasksSettings = Seq(
    kazariDefaultPath := target.value.getPath + "/" + "scala-2.11",
    kazariPluginFilename := "kazari.js",
    fastOptSuffix := "-fastopt.js",
    fullOptSuffix := "-opt.js",
    jsDepSuffix := "-jsdeps.js",
    jsFastOptAssembleTask := concatFiles(
      kazariDefaultPath.value,
      Seq(moduleName.value + jsDepSuffix.value, moduleName.value + fastOptSuffix.value),
      kazariPluginFilename.value),
    jsFullOptAssembleTask := concatFiles(
      kazariDefaultPath.value,
      Seq(moduleName.value + jsDepSuffix.value, moduleName.value + fullOptSuffix.value),
      kazariPluginFilename.value),
    jsFastOptGenerateTask := Def
      .sequential(
        fastOptJS in Compile,
        jsFastOptAssembleTask
      )
      .value,
    jsFullOptGenerateTask := Def
      .sequential(
        fullOptJS in Compile,
        jsFullOptAssembleTask
      )
      .value
  )
}
